version: '3'

services:
  achievable_database:
    image: citusdata/citus:10
    container_name: rmp_database
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_PASSWORD: rmp_13579qe123
      POSTGRES_USER: rmp_user
      POSTGRES_DB: rmp_database
    ports:
      - 5555:5432
    networks:
      - app-network
    volumes:
      - ./postgres:/var/lib/postgresql/data

#Docker Networks
networks:
  app-network:
    driver: bridge
