version: '3'

services:
  rmp_database:
    image: citusdata/citus:10
    container_name: rmp_database
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_PASSWORD: rmp_13579qe123
      POSTGRES_USER: rmp_user
      POSTGRES_DB: rmp_database
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - ./postgres:/var/lib/postgresql/data
  rmp_nestjs:
    depends_on:
      - rmp_database
    build: .
    container_name: rmp_nestjs
    restart: unless-stopped
    hostname: rmp_nestjs
    tty: true
    env_file:
      - ./.env
    ports:
      - 80:1234
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
